import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";
import { SplitPdf } from "../components/SplitPdf";
import { SITE_URL } from "../lib/site";

export const metadata: Metadata = { title: { absolute: "Split PDF & Extract Pages Online Free | PDF Slate" }, description: "Split a PDF by extracting or removing selected pages. Free, private browser processing with no uploads, login, payment, or watermark.", alternates: { canonical: `${SITE_URL}/split-pdf` }, openGraph: { title: "Split a PDF or extract pages privately", description: "Choose page ranges and create a new PDF without uploading the original.", url: `${SITE_URL}/split-pdf`, siteName: "PDF Slate", type: "website" } };
const faqs = [{ question: "How do I split a PDF?", answer: "Choose a PDF, enter pages such as 1-3, 5, 8-10, then extract those pages or remove them from a new copy." }, { question: "Can I extract several page ranges?", answer: "Yes. Separate individual pages and ranges with commas. The extracted pages stay in their original document order." }, { question: "Does splitting upload my document?", answer: "No. The PDF is opened and rebuilt locally in your browser." }, { question: "Does splitting change the original PDF?", answer: "No. PDF Slate downloads a new document and never alters the source file on your device." }];
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
export default function SplitPdfPage() { return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} /><SiteHeader /><main className="protect-main"><section className="protect-hero" aria-labelledby="split-title"><p className="eyebrow"><span>●</span> Private page extraction</p><h1 id="split-title">Split a PDF online.<br /><em>Keep only the pages you need.</em></h1><p>Extract selected pages or remove unwanted ones, then download a fresh PDF. Nothing is uploaded or stored.</p></section><section className="protect-tool-section"><SplitPdf /></section><section className="content-section protect-explainer"><div className="section-intro centered"><p className="eyebrow">Three simple steps</p><h2>How to split or extract PDF pages</h2></div><ol className="steps-grid"><li><span>01</span><div className="step-icon">↥</div><h3>Choose your PDF</h3><p>Select a document up to 50 MB from your device.</p></li><li><span>02</span><div className="step-icon">1-3</div><h3>Enter page ranges</h3><p>Choose pages to extract or remove using simple range notation.</p></li><li><span>03</span><div className="step-icon">↓</div><h3>Download the result</h3><p>Save a new PDF containing exactly the pages you requested.</p></li></ol></section><section className="content-section faq-section"><div className="section-intro centered"><p className="eyebrow">Good to know</p><h2>Split PDF FAQ</h2></div><div className="faq-list">{faqs.map((faq, index) => <details key={faq.question} open={index === 0}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></section></main><SiteFooter /></>; }
