import type { Metadata } from "next";
import { MergePdf } from "../components/MergePdf";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";
import { SITE_URL } from "../lib/site";

export const metadata: Metadata = { title: { absolute: "Merge PDF Files Online Free & Privately | localpdf.store" }, description: "Merge multiple PDF files into one document in your chosen order. Free and private in your browser with no uploads, login, or watermark.", alternates: { canonical: `${SITE_URL}/merge-pdf` }, openGraph: { title: "Merge PDFs privately in your browser", description: "Arrange and combine PDF files without uploading them.", url: `${SITE_URL}/merge-pdf`, siteName: "localpdf.store", type: "website" } };
const faqs = [{ question: "How do I merge PDF files?", answer: "Choose two or more PDFs, arrange them using the arrow buttons, then select Merge & download PDF." }, { question: "Are my PDFs uploaded?", answer: "No. Every source PDF is read and combined locally in your browser." }, { question: "How many PDFs can I combine?", answer: "You can merge up to 20 PDFs, with a combined limit of 150 MB." }, { question: "Can I merge password-protected PDFs?", answer: "Unlock them first in a trusted PDF app. The merger does not ask for or remove existing passwords." }];
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
export default function MergePdfPage() { return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} /><SiteHeader /><main className="protect-main"><section className="protect-hero" aria-labelledby="merge-title"><p className="eyebrow"><span>●</span> Private PDF organizer</p><h1 id="merge-title">Merge PDF files online.<br /><em>Keep every page private.</em></h1><p>Combine PDFs in the exact order you choose. The work happens on your device with no uploads, account, payment, or watermark.</p></section><section className="protect-tool-section"><MergePdf /></section><section className="content-section protect-explainer"><div className="section-intro centered"><p className="eyebrow">Three simple steps</p><h2>How to combine PDF files</h2></div><ol className="steps-grid"><li><span>01</span><div className="step-icon">+</div><h3>Add your PDFs</h3><p>Select between 2 and 20 PDF documents from your device.</p></li><li><span>02</span><div className="step-icon">↕</div><h3>Arrange the order</h3><p>Move each PDF up or down to control the final page sequence.</p></li><li><span>03</span><div className="step-icon">↓</div><h3>Merge and download</h3><p>Create one PDF containing every page in your chosen order.</p></li></ol></section><section className="content-section faq-section"><div className="section-intro centered"><p className="eyebrow">Good to know</p><h2>Merge PDF FAQ</h2></div><div className="faq-list">{faqs.map((faq, index) => <details key={faq.question} open={index === 0}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></section></main><SiteFooter /></>; }
