import type { Metadata } from "next";
import { PdfFiller } from "../components/PdfFiller";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";
import { SITE_URL } from "../lib/site";

export const metadata: Metadata = { title: { absolute: "Fill PDF Forms Online Free & Privately | PDF Slate" }, description: "Fill PDF form fields or add text to a PDF privately in your browser. Free, with no upload, account, payment, or watermark.", alternates: { canonical: `${SITE_URL}/fill-pdf` }, openGraph: { title: "Fill PDF forms privately online", description: "Complete and download a PDF without uploading it.", url: `${SITE_URL}/fill-pdf`, siteName: "PDF Slate", type: "website" } };
const faqs = [
  { question: "Can I fill a PDF online for free?", answer: "Yes. Complete interactive fields or place text on a flat PDF, then download it with no account, payment, or watermark." },
  { question: "Is my PDF uploaded?", answer: "No. The PDF is opened, edited, and saved by code running in your browser." },
  { question: "Can I fill a PDF with no form fields?", answer: "Yes. Use Place text and click where the text should appear on the page." },
  { question: "Are XFA forms supported?", answer: "Not currently. The tool detects XFA and explains the limitation rather than creating an unreliable result." },
];
const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
export default function FillPdfPage() { return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} /><SiteHeader /><main className="protect-main"><section className="protect-hero" aria-labelledby="fill-title"><p className="eyebrow"><span aria-hidden="true">●</span> Private PDF form filler</p><h1 id="fill-title">Fill a PDF online.<br /><em>Keep it on your device.</em></h1><p>Complete detected form fields or place text onto any page, then download a new copy. No upload, login, payment, or watermark.</p></section><section className="dedicated-fill-tool" aria-label="Fill PDF tool"><PdfFiller /></section><section className="content-section protect-explainer" aria-labelledby="fill-how"><div className="section-intro centered"><p className="eyebrow">Simple by default</p><h2 id="fill-how">How to fill a PDF online</h2></div><ol className="steps-grid"><li><span>01</span><div className="step-icon">↥</div><h3>Choose your PDF</h3><p>Select a standard PDF form or a flat document from your device.</p></li><li><span>02</span><div className="step-icon">Aa</div><h3>Complete the details</h3><p>Fill detected controls or place text exactly where it belongs.</p></li><li><span>03</span><div className="step-icon">↓</div><h3>Download your copy</h3><p>Lock field values for consistent viewing or keep them editable.</p></li></ol></section><section className="content-section faq-section"><div className="section-intro centered"><p className="eyebrow">Good to know</p><h2>PDF form filler FAQ</h2></div><div className="faq-list">{faqs.map((faq, index) => <details key={faq.question} open={index === 0}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></section></main><SiteFooter /></>; }
